CREATE ROLE dev_db WITH LOGIN ENCRYPTED PASSWORD 'dev_pw';
ALTER USER dev_db WITH SUPERUSER;
CREATE DATABASE dev_db;
GRANT ALL PRIVILEGES ON DATABASE dev_db TO dev_db;

CREATE ROLE test_db WITH LOGIN ENCRYPTED PASSWORD 'test_pw';
ALTER USER test_db WITH SUPERUSER;
CREATE DATABASE test_db;
GRANT ALL PRIVILEGES ON DATABASE test_db TO test_db;

CREATE ROLE prod_db WITH LOGIN ENCRYPTED PASSWORD 'prod_pw';
ALTER USER prod_db WITH SUPERUSER;
CREATE DATABASE prod_db;
GRANT ALL PRIVILEGES ON DATABASE prod_db TO prod_db;